nativefier/nativefier

- README.md
an native desktop app => a native desktop app
can built => can be built
> Minor copy fixes

- README.md
> Add the missing http://

- app/src/main.js
- app/src/preload.js
Any time a new Notification is constructed, atom is notified and the badge is displayed.
I wasn't able to test this much, so LMK how it works for you.
> add notification monkey-patch, closes #38

- app/src/components/mainWindow/mainWindow.js
> Add icon hotfix

- README.md
Noticed that usage of `-V`option was missing in Readme , so I would update
> Update Readme to add usage of -V option

- app/src/main.js
> Revert "flash support #2"

- app/src/components/mainWindow/mainWindow.js
- docs/api.md
- src/build/buildApp.js
- src/cli.js
- src/options/optionsMain.js
I have added the maximize option for the MainWindow, where the browser window would maximize upon initial application launch, as agreed in the ticket: #133
> Added option for maximization of main window ( #133 )

- src/infer/inferUserAgent.js
- src/options/optionsMain.js
Fixes #166. See discussion there for further details!
> Infer user agent from Electron's online version list

- app/src/components/mainWindow/mainWindow.js
- docs/api.md
- src/build/buildApp.js
- src/cli.js
- src/options/optionsMain.js
> Add an option to disable the context menu

- app/src/components/mainWindow/mainWindow.js
- docs/api.md
- src/build/buildApp.js
- src/cli.js
- src/options/optionsMain.js
> Add an option to hide window frame and controls

- app/src/components/mainWindow/mainWindow.js
- app/src/main.js
- docs/api.md
- src/build/buildApp.js
- src/cli.js
- src/options/optionsMain.js
> make keeping os x apps running optional

- app/src/main.js
- docs/api.md
- src/build/buildApp.js
- src/cli.js
- src/options/optionsMain.js
It's my first time working with Electron, so please let me know if this is a completely ridiculous way to implement this feature!
> Crash Reporting

- docs/development.md
https://github.com/jiahaog/nativefier/issues/290
https://github.com/jiahaog/nativefier/issues/286
> just change ordering so it does not misslead

- package.json
You have duplicate packages in you `dependecies` and `devDependencies`.
> Remove duplicate dependencies

- docs/changelog.md
Removing duplicate entries, separate new features as such, order by features>fixes>rest
> Cleanup 7.1.0 changelog

- docs/api.md
> Add entry for hide-window-frame to Table of Contents in api.md

- package.json
See https://github.com/tjunnone/npm-check-updates/issues/355
@jiahaog @darrenhaken just a deps upgrade, please merge
> Fix build broken in Node 8.x

- docs/changelog.md
- package.json
A few users asked for a release bundling recent fixes, let's do that.
@jiahaog letting you create the tag/release too, or I can do it once this is merged.
> Release 7.4.1

- src/cli.js
Nativefier now detects if the user has a working internet connection, and gives advice on offline builds as per #448
> Add offline build detection and advice

- app/src/components/mainWindow/mainWindow.js
- app/src/components/trayIcon/trayIcon.js
- app/src/main.js
- docs/api.md
- src/build/buildApp.js
- src/cli.js
- src/options/optionsMain.js
#304
Maybe we can improve this with a support of badges and counters, like to change the icon with an dynamically generated icon with the badge... (ref : https://github.com/electron/electron/issues/3148)
> Add "--tray" option to allow app to stay in the system tray

- Dockerfile
Feedback welcome @toschneck @filippobuletto
- Should address #375 (building a win app from linux) under Docker, thanks @dipenpatel235 for the suggestion to use `wine32` at #375 (comment)
- Regarding #461, [Docker build](https://hub.docker.com/r/jiahaog/nativefier/builds/) seems fine but it was already fine for some time, not sure what happened.
Also clean up a bit the Dockerfile using suggestions from Dockerfile linter [hadolint](https://github.com/lukasmartinelli/hadolint/).
> Fix #461 & address #375 in Docker: move Dockerfile to Debian and use wine32

- src/cli.js
> Fix #496 - Recommend .png for --icon on all platforms

- .eslintrc.yml
- app/package.json
- app/src/helpers/helpers.js
- app/src/helpers/inferFlash.js
- app/src/static/preload.js
- gulp/watch.js
- src/build/buildApp.js
- src/cli.js
- src/helpers/packagerConsole.js
- test-resources/test-injection.js
- test/module/getIconSpec.js
> Change logging method to loglevel

- app/src/components/mainWindow/mainWindow.js
- docs/api.md
- src/build/buildApp.js
- src/cli.js
- src/options/optionsMain.js
Add `--x` and `--y` flags to set default window position
Fixes #325
> Add window position flags

- app/src/components/mainWindow/mainWindow.js
- docs/api.md
- src/build/buildApp.js
- src/cli.js
- src/options/optionsMain.js
Modal feature added using --always-on-top build-time flag.
> FIX #549: Always on top window flag.

- src/infer/inferUserAgent.test.js
There is a lint error in `inferUserAgent.test.js` on master.  This PR fixes it.
> Fix `prettier` lint error

- app/src/components/mainWindow/mainWindow.js
- docs/api.md
- src/build/buildApp.js
- src/cli.js
- src/options/optionsMain.js
Add an option to set proxy rule.
> feat: proxy rules

- src/infer/inferOs.ts
I believe this should fix #804 based on comments there, but I need to figure out how to test it.
> Support architecture arm64 (fix #804)

- README.md
otherwise it makes and keeps a randomly named container around forever.
for example, after trying a few times to create a container with some different args, my local docker environment looks like this:
```
$ docker ps -a
CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS                      PORTS                  NAMES
8a9f6cf954e9        jiahaog/nativefier:latest           "nativefier --name s…"   33 minutes ago      Exited (0) 33 minutes ago                          funny_haibt
cac423bddde3        jiahaog/nativefier:latest           "nativefier --name s…"   36 minutes ago      Exited (0) 36 minutes ago                          nostalgic_black
d5146bf1bd13        jiahaog/nativefier:latest           "nativefier --name s…"   36 …
```
> README: suggest docker "-rm" flag to clean up containers after build

- app/src/main.ts
- docs/api.md
- package.json
- src/build/prepareElectronApp.ts
- src/cli.ts
- src/options/model.ts
- src/options/optionsMain.ts
> Warn on old Electron/Chrome (fix #556)

- README.md
- docs/api.md
- icon-scripts/convertToIcns
- icon-scripts/convertToIco
- icon-scripts/convertToIconset
- icon-scripts/convertToPng
- src/helpers/helpers.ts
Work in progress. Comments welcome.
> Icon conversion: support GraphicsMagick in addition to  ImageMagick

- docs/development.md
An attempt to a few important things to newcomers, to reduce risk of contributors being disappointed / contradicted late at PR time.
@TheCleric your fresh eyes are welcome: anything to add/change?
> Dev.md: guidelines

- app/src/main.ts
Enhancement for https://github.com/nativefier/nativefier/issues/405
> Support opening URLs passed as arg to Nativefied application (fix #405)

- README.md
- app/src/helpers/helpers.test.ts
- app/src/helpers/helpers.ts
- src/constants.ts
When doing some testing of other Google apps, I found an SSO endpoint that Google was trying to redirect through. PR to add it.
> Add newly discovered Google internal login page

- app/src/main.ts
Fixes regression in https://github.com/nativefier/nativefier/commit/f6e1ebd876c257074565ef205212081ca5865974 .
Also, fixing a typo I missed in the PR, and adding types for callback params.
> Fix app not starting since widevine PR / #1164

- app/src/components/mainWindow.ts
Fixes #939 
Error was due to the fact that we try to inject CSS into the known window on all web requests, which crashes when a tab is closed since that window doesn't exist anymore. Now we'll check to see if the request has its own webContents (which it won't for stuff like XHR, JS files, etc.) and inject into there.
> Only try to inject css for valid web requests (fix #939 - crash on tab close)

- app/src/main.ts
```
Uncaught Exception:
TypeError: Cannot read property 'show' of undefined
at App.<anonymous> (/src/main.ts:177:18)
```
Seems like an oversight of the recent refactor.
@TheCleric not 100% sure about it as I don't have a mac to test, so letting you test/finish/merge. Will make a quick release once this is merged.
> macOS: fix crash on activating main window (fix #1212)

- app/src/components/mainWindow.ts
- app/src/helpers/windowEvents.ts
By adding a new window handler only to the main window.
> Fix tabs opening twice (fix #1209)

- .github/manual-test
- app/src/components/loginWindow.ts
- app/src/main.ts
Should resolve #1219 as well adds a manual test for basic auth as suggested.
> Fix HTTP basic auth (fix #1219)

- README.md
Update required `node` and `npm` versions
> Update node requirements info

- app/src/components/trayIcon.ts
- src/cli.test.ts
Fix regression introduced in #1235
> Fix tray icon always on (regression from #1235)

- app/src/components/menu.test.ts
- app/src/components/menu.ts
- app/src/helpers/windowHelpers.ts
> Fix "Reset Zoom" menu item (fix #1241)

- app/src/components/contextMenu.ts
These options are very useful for image handling and should be included.
> App context menu: Add electron-context-menu image entries (Save Image, Copy Image, Copy Image Address)

- .gitignore
- package-lock.json
- package.json
- src/cli.ts
Yargs coerce has seemed to stop working (though it works in minimal examples on my machine; not sure why).
For now we'll manually coerce to ensure it actually happens.
> Workaround yargs coerce issue

- .github/manual-test
- app/package-lock.json
- app/package.json
- app/src/components/mainWindow.ts
- app/src/helpers/windowEvents.ts
- app/src/helpers/windowHelpers.test.ts
- app/src/helpers/windowHelpers.ts
- app/src/mocks/electron.ts
- shared/src/options/model.ts
- src/constants.ts
> Fix regressions in opening windows/tabs, update browser versions

- API.md
- src/cli.ts
> Allow setting default app destination with env. var. NATIVEFIER_APPS_DIR

- app/src/components/menu.ts
> Change Paste and Match Style shortcut to match Apple's HIG advice (fix #404)

- app/src/components/contextMenu.ts
- app/src/helpers/windowEvents.ts
Hi @ronjouch , long time no talk!
Should fix #1260
> macOS: fix Open In New Tab (fix #1260)

- .github/workflows/ci.yml
- app/src/main.ts
- npm-shrinkwrap.json
- package.json
https://jestjs.io/blog/2022/04/25/jest-28
https://jestjs.io/docs/upgrading-to-jest28
https://github.com/facebook/jest/blob/main/CHANGELOG.md#2800
Causes playwright tests to fail in CI & on my machine,
but I can't troubleshoot because they fail differently
(always have been) on my machine :-/ .
> Bump jest to 28

- app/src/components/mainWindow.ts
- app/src/main.ts
> macOS: Fix "main window cannot be activated" (fix #1415)

- CATALOG.md
Added injected css to make WhatsApp more native-like in macOS
> WhatsApp custom CSS for native-looking app on macOS
