usage.txt
Removed "--target" in example and add quotes to make sure the shell interpreter does not try to interpret certain characters like ? or & in the url
=> Fix error in usage example

src/options.js
This commit resolves an bug where the page title would cause a filepaths
issue due to it having a forward slash.
The code committed here uses a simple regular expression to find all
instances of forward slashes in the page title and replace them with an
empty string.
Resolves #22
For more on this, please see:
https://github.com/jiahaog/nativefier/issues/22
=> Fixes the issue with "/"'s in the page title

src/options.js
This could be a great way to package intranet applications into electron apps. Added `require_tld` validator config setting to allow those intranet locations without a TLD to be packaged.
=> Allow intranet URLs

README.md, app/nativefier.json, app/src/main.js, src/buildApp.js, src/cli.js, src/options.js
This PR closes #41.
It adds the `-m`, `--show-menu-bar` option in order to make the menu bar visible. By default, it's hidden.
=> Adding hide/show menu bar option

README.md, src/cli.js
There're two `-h` options we can choose on cli :
```
-h, --help                      output usage information
...
-h, --height <value>            set window height, defaults to 800px
```
`-h, --help` option is automatically added by `npm commander` module and it seems to be difficult to change its syntax.
So , I'd like to change `src/cli.js` to fix these options to avoid conflict :
`-h, --height <value>`  => `--height <value>`
`-w, --width <value>`   => `--width <value>`        (to make syntax even)
also I changed usage manual in readme.md.
This problem is reported from Issue #64
=> Fix -h option's conflict from Issue #64

index.js, package.json, src/cli.js, src/main.js
- Refactored `main` function into another file
- Expose `main` instead of `buildApp` to utilize `optionsFactory`
=> Expose main instead of buildApp

src/options.js
- Prevents undesired behavior due to default kebab casing when user names his own apps.
=> Respect user choice for naming

app/src/components/mainWindow/mainWindow.js
This PR adds support for [x] and {x} forms of notification counters in the page title, instead of just (x).
=> counter: Allow for [x] and {x} forms of notification count

app/src/components/menu/menu.js
I often need to copy the current webpage link to paste into other apps/windows/browsers, and the current bind was being overwritten by "Copy"
=> Rebind 'Copy Current URL' to 'CmdOrCtrl+L' to mimic 'Open Location'

app/src/components/mainWindow/mainWindow.js
This reverts commit eeb661b6cd82a3f21f5adbf0d1389cf2804fd16b.
fixes #191 
This was causing injected CSS to pile up over and over each time javascript did an HTTP request, which resulted in massive slowdown over time.  For sites that do a lot of HTTP requests (example: hangouts during a call), things can get unbearably slow very quickly and CPU usage hits 100% until you reload with ctrl-R.
I'm not sure how to fix the flash of unstyled content (FOUC) fixed by eeb661b6cd8 but I haven't had that issue.
=> Revert "Fix FOUC with inject CSS files"

app/src/components/mainWindow/mainWindow.js, app/src/helpers/helpers.js, app/src/static/preload.js
Fixes #191 
- Use `did-navigate` instead of `did-start-loading` to trigger the injection of css on every page. This is because Electron somehow triggers a `did-start-loading` event on ajax events without having a `did-finish-load` event to indicate completion even after `did-finish-load` has triggered on a page, which will cause the injection of css through `did-get-response-details` to continue indefinitely on every ajax request. Take note that to avoid the flash of unstyled content, the current behaviour of injecting css on `did-get-response-details` is maintained, which triggers many times until `did-finish-load`. This runs ~50 times or so on loading the YouTube home page, but it does not appear to affect performance because the injection of css stops the moment `did-finish-load` …
=> Fix/performance issues with FOUC

app/src/components/mainWindow/mainWindow.js, docs/api.md, src/build/buildApp.js, src/cli.js, src/options/optionsMain.js
These changes add the ability to declare a default zoom factor for an application with the `--zoom` flag. While it doesn't fix #125 directly, it at least seems like a better workaround than the one mentioned in the issue.
=> Added a --zoom option for setting default zoom

src/options/optionsMain.js
the sanitizeFilename function only remove one none ascii char
The exe name should be "微信网页版.exe", not "信网页版.exe".
=> remove all non ascii or use default app name

app/src/components/contextMenu/contextMenu.js, app/src/components/mainWindow/mainWindow.js, app/src/helpers/helpers.js, src/build/buildApp.js, src/cli.js, src/options/optionsMain.js
Two mostly unrelated features -- let me know if these should be separate PRs.
* "copy link location" for context menu -- kept meaning to add this and finally got around to it
* "--internal-urls <regex>" argument to override the default method used to determine which URLs should stay in the nativefied app.  In google inbox, for example, I want google docs to open in my main browser.  Regex gives the user a lot of flexibility.
=> add "copy link location" and "--internal-urls <regex>" features

app/src/components/mainWindow/mainWindow.js, app/src/main.js
This refactors and improves on the badge notification setup. I've centralized and streamlined the logic for badge behavior all to a single if/else block in `createMainWindow`, so that it is easier to reason about as a whole. I believe the intended behavior is as follows:
- When using the `counter` option, a numbered badge should appear on the app icon corresponding to the window title, whether focused or not. If no number can be parsed, then no badge should appear.
- When not using the `counter` option, the `•` badge should appear when a notification is sent, and should clear when the app is focused. (I made a slight tweak to use the smaller `•` instead of `●`, which looks a bit more native to my eye.)
Along the way, I fixed the `page-title-updated` listener to use the `title` argument …
=> Fix counter notifications

app/src/static/preload.js
Test case: open nativefier on
```html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Test</title>
</head>
<body>
<a href="https://google.com/">Google</a>
<br>
<a href="https://google.com/"><span>Google, in span</span></a>
</body>
</html>
```
and try to `Right Click` → `Open in Default Browser` both links.
* **Expected**: both links open in default browser
* **Actual under nativefier 7.0.1**: Nothing happens when clicking the second link in which the `<a>` contains a `<span>`
=> Fix context menu actions broken on <a> elements containing nested markup

docs/api.md
It was a bit unclear that we needed those dependencies, especially if just referring to the api docs and not the main readme.
=> Linked optional dependencies for generating icons

README.md
The link to the changelog on [npmjs.com](https://www.npmjs.com/package/nativefier) links to the master branch, which doesn't exist. Not sure if there's a better fix, but I swapped it for an absolute URL instead.
=> Absolute link to changelog

app/src/components/contextMenu/contextMenu.js
in most users, `Open with` more popular and familiar rather than `Open in`
=> Update contextMenu label

app/src/main.js, docs/api.md, src/build/buildApp.js, src/cli.js, src/options/optionsMain.js
This PR adds a `--single-instance` option that prevents application from being run multiple times. If such a situation occurs, the already running instance is brought to front.
Fixes #322.
=> Add --single-instance switch

app/package.json, package.json, src/infer/inferUserAgent.js, src/options/optionsMain.js, test/module/inferUserAgent-spec.js
Do ***NOT*** merge this PR right now, it deserves some time of cross-OS testing.
=> Fix #327 - Update dependencies, enforce Node>=4.0, and default to Electron 1.6.6

app/src/components/mainWindow/mainWindow.js, app/src/components/menu/menu.js
* When zooming in/out, start from the options zoom, not 1 (don't jump)
* Add 'Zoom Reset' feature bound to Ctrl+0, with indicative label for non-100% zoom value
=> Fix #253 - Better honor --zoom option.

src/options/optionsMain.js
=> Fix for executable name being 'Electron' always under Windows, Issue #28

app/src/main.js, docs/api.md, src/build/buildApp.js, src/cli.js, src/options/optionsMain.js
Electron [now has support](https://github.com/electron/electron/pull/9435) for this flag, and I found it useful to expose it in Nativefier. I have an app that needs to cache som larger files, and it was unable to do so without increasing the cache size. This PR solved the issue for me—and maybe the flag will be useful to someone else too.
=> Added support for --disk-cache-size

app/src/main.js, docs/api.md, src/build/buildApp.js, src/cli.js, src/options/optionsMain.js
Add options (--ignore-gpu-blacklist and --enable-es3-apis) to allow for WebGl apps to work on legacy or unsupported graphics cards by Chrome
=> New feature: options for --ignore-gpu-blacklist and --enable-es3-apis Chrome flags

app/src/components/mainWindow/mainWindow.js
Fixes #402, as electron-window-state does not appear to remember fullscreen in all cases.
=> Force fullscreen when options.fullScreen is true

app/src/components/mainWindow/mainWindow.js
Some websites use this format in their title count: `(9+)`.
This commit adds support for those and it will not affect the previous behavior.
=> Update title counter regex

docs/api.md, package.json, src/build/buildMain.js, src/cli.js, src/options/optionsMain.js
See Issue https://github.com/jiahaog/nativefier/issues/226.
Added support for `app-copyright`, `app-version`, `build-version`, `version-string` and `win32metadata`.
Similar to PR https://github.com/jiahaog/nativefier/pull/228, but I also needed `build-version`.  I also included support for `win32metadata` since that was recently added to `electron-packager` (v8.0.0) making `version-string` deprecated.
`app-copyright`, `app-version`, `build-version` are supported in the CLI but `version-string` and `win32metadata` only supported via the [Nativefier Programmatic API](https://github.com/jiahaog/nativefier/blob/development/docs/api.md#programmatic-api).
=> Fix #226 - Added support for app-copyright, app-version, build-version, version-string and win32metadata

src/build/buildApp.js
Ok, I think that these params were left out of one of the PR's that I made.  Fixes issue #438.
=> fix: add new params to buildApp (issue #438)

app/src/components/mainWindow/mainWindow.js, app/src/components/trayIcon/trayIcon.js, app/src/helpers/helpers.js
#486
When building Windows app, "icon.png" doesn't exists but it generates an "icon.ico", so I created a function in helpers.js that returns the correct icon file. I don't know what can happen on OSX (I can't test it), I saw that there is a conversion to an ".icns" file, maybe we must also handle OSX icon file in this helper function.
Also fix Windows specific error on tray icon load (like on this comment : https://github.com/electron/electron/issues/7657#issuecomment-317073318)
=> Fix #486 for windows : missing icon.ico

docs/api.md, src/build/buildMain.js, src/cli.js, src/infer/inferOs.js, src/infer/inferUserAgent.js, test/module/inferUserAgentSpec.js
I needed to roll a nativefied app that would pass the Mac Application Store's checks, which rejects some of the now deprecated QuickTime API's included in the `osx` or `darwin` builds.
This extends nativefier to support `--platform=mas`, which is already supported by the underlying `electron-packager` dependency.
=> Add support for MAS builds

docs/api.md
Update readme to include documentation on `internal-urls` option
=> Document internal-urls option

app/src/components/mainWindow/mainWindow.js, app/src/static/preload.js
The method of setting the zoom factor on the web frame inside of the renderer doesn't persist across navigation, as reported in #474. This change replaces instances of sending the 'change-zoom' event with calls to the setZoomFactor webContents API.
=> FIX #474: Use setZoomFactor instead of sending change-zoom event

app/src/main.js, docs/api.md, src/build/buildApp.js, src/cli.js, src/options/optionsMain.js
This change closes #364 by adding a `--disable-gpu` flag to nativefier which causes the built app to call `app.disableHardwareAcceleration()` at startup.
=> FIX #364: Add --disable-gpu flag to disable hardware acceleration

src/build/iconBuild.js
This fixes #573 by allowing the build to continue without errors after the icon conversion fails.
=> FIX #573: Unset options.icon if input cannot be converted

src/build/buildMain.js
By default, the tmp module creates directories with permissions `0700`.  It appears that the `app` folder created by `buildApp` has its permissions set to those of the enclosing folder, so this results in the behavior reported in #575. By setting the tmp dir permissions explicitly to `0755`, as this change does, the `app` folder also gets those permissions, thereby resolving the issue.
=> FIX #575: Create tmp dir with mode 0755

app/package.json, app/src/components/contextMenu/contextMenu.js, app/src/components/mainWindow/mainWindow.js, app/src/static/preload.js
The electron-context-menu package uses the context-menu event emitted by WebContents (API added in Electron 1.0.2) to add a general context menu supporting generic actions (e.g. cut/copy/paste) that can be customized.
This change replaces the existing context menu, which relies on adding an event listener in preload.js, with one built using the new package. It fixes #95 and #384.
=> Add electron-context-menu dependency

README.md, bin/convertToIcns, bin/convertToIconset, bin/convertToPng
This change eliminates the requirement for imagemagick to be present on macOS for icon conversion.
This PR is based off of the code from #279 and fixes #199.
=> FIX #199: Add support for using sips when available

app/src/components/contextMenu/contextMenu.js, app/src/components/mainWindow/mainWindow.js
As described in #590, new windows are not being configured properly. This change refactors window creation so that a common base set of window behaviors can be shared between the mainWindow and new windows that are created.
=> FIX #590: Ensure secondary windows have the same behaviors as the mainWindow

app/src/components/mainWindow/mainWindow.js
This fixes the issue where Gmail complains that new window creation was prevented by a popup blocker.
=> Change incorrect guest property to newGuest

app/src/components/mainWindow/mainWindow.js
As part of #591, all window creation was routed through a createNewWindow function.  That change introduced the regression reported in #616 in which popup windows could not communicate with their parent windows. This change reverts that behavior for windows opened via JavaScript (that aren't being opened as tabs and aren't being opened in external browsers), thereby fixing the reported regression.
=> Only override the default window opening behavior when necessary

app/src/components/mainWindow/mainWindow.js
The tab feature introduced by #579 included a change that checks the `disposition` parameter and conditionally creates tabs, and that check was placed prior to the check to see if the URL is internal. This change moves the `linkIsInternal()` check earlier so that external links are always opened externally, regardless of disposition.
This change fixes #621.
=> Always open external links externally

app/src/components/mainWindow/mainWindow.js
This PR makes it so any navigation to an external link results in the link being opened in an external browser. The current behavior is to only do so for links with target="_blank", or those opened via window.open().
=> Force all external links to be opened externally

app/src/components/mainWindow/mainWindow.js, app/src/components/mainWindow/mainWindowHelpers.js, app/src/components/mainWindow/mainWindowHelpers.test.js, app/src/helpers/helpers.js, app/src/helpers/helpers.test.js
When you open some links with Google Calendar, instead of opening the link directly, the site opens a new window with the location `about:blank` and then sets the new window's document content to include a refresh directive to open the actual link.
Without this change, the links in Google Calendar do nothing when clicked, because `about:blank` is passed to `shell.openExternal()`, which does nothing with it.
This PR consists of multiple changes:
* The `linkIsInternal()` function has been updated to treat `about:blank` links as internal so that the redirect technique can work at all. However, while this works, the redirect itself causes another window to be opened (in the external browser), leaving behind a blank, useless window in the nativefier app.
* Tests have been added for …
=> Fix sites that use about:blank redirect technique

app/src/components/mainWindow/mainWindow.js, app/src/components/trayIcon/trayIcon.js, app/src/helpers/helpers.js, app/src/helpers/helpers.test.js
When using an app such as Gmail, the unread count is included in the title, and the --counter feature displays that number on the dock icon. However, when the number is larger than 999, it includes commas in the number (e.g. "1,000"), and the number is no longer displayed on the dock icon, because the regular expression used to detect the counter value does not permit punctuation.
This change modifies the regular expression used to match the counter value to permit "." and ",".
=> Make the counter regexp allow punctuation

app/src/components/mainWindow/mainWindow.js, docs/api.md, src/build/buildApp.js, src/cli.js, src/options/optionsMain.js
Hello,
This PR, which partly addresses #35, is to include a CLI option to specify an alternative title bar style for macOS. Available values include 'hidden' and 'hiddenInset' as specified [here](https://github.com/electron/electron/blob/master/docs/api/frameless-window.md#alternatives-on-macos).
Would you please consider merging?
=> Add cli option to set titleBarStyle

src/cli.js
Most Unix-based command line utilities respond to a _lowercase_ `-v` flag which outputs the current version. Adding that as an alias here in addition to the already present `--version` and `-V` flags :)
=> Add Unix/Mac-conventional `-v` version flag

app/src/components/mainWindow/mainWindow.js
When the `getCurrentUrl` function was refactored to make use of the `withFocusedWindow` function in ac99c6424d7326ad7d1da86922866e6776ce3220, it stopped returning a value and broke the "Copy Current URL" feature (#633).
This change restores the original behavior of the getCurrentURL function and makes the "Copy Current URL" feature functional again.
=> Make `getCurrentUrl` actually return something

app/src/components/mainWindow/mainWindow.js, app/src/static/preload.js
There currently is an issue where the nativefied application does not respond to clicking on a desktop notification. You would expect it to restore and focus its window, but that doesn't work if:
- The window is minimized
- There is no open window (macOS)
See #221 and possibly #396.
This PR fixes that by adding a click handler to each notification. When clicking the notification the Electron app restores and focuses the main window using BrowserWindow.show(). This seems to handle both cases (restore minimized window / open new window, then focus window).
=> Restore application window on notification click

docs/api.md
On Windows, the supplied icon needs to be in .ico format
Closes #239
=> Update docs about icon requirements on Windows

docs/api.md
The `--counter` option mentioned a _badge option_, which doesn't appear in the docs. This change removes this as it is not relevant in the context.
=> Remove mention to older badge option in docs

src/cli.js
This updates URLs in the command-line help to avoid redirects.
=> Update documentation URLs in the CLI help message

app/src/components/mainWindow/mainWindow.js
A very basic change to fix #703. I only changed the deprecated `did-get-response-details` event to the recommended alternative: `webRequest.onHeadersReceived`.
All tests that I done with navigation and prevention of FOUC passed using the same command of the issue (`nativefier "https://www.w3schools.com" --inject ./main.css --overwrite`).
=> Fix Electron 3 CSS injection (#703)

app/src/components/mainWindow/mainWindow.js, docs/api.md, src/cli.js
This fixes #522 by introducing `--start-in-tray` as new CLI flag.
=> Fix #522 - Add --start-in-tray CLI flag to let app start in background

app/src/components/mainWindow/mainWindow.js, app/src/static/preload.js, docs/api.md
These commits address #703, #731 by fixing the two core issues:
1. #703, was caused by null filters being passed to `onHeadersReceived`. Passing `[]` resolves the issue
2. #731, was caused by a timing issue of when `DOMContentLoaded` was attached vs raised.
Each commit contains the full details. Also updates `api.md` with some extra context about when injected JavaScript is inserted
=> Address CSS & JavaScript injection issues (#703, #731)

src/helpers/convertToIcns.js, src/helpers/iconShellHelpers.js
Currently having spaces in folders causes the icon conversion to crash. This PR fixes the issue.
=> Allow spaces in folder names

app/package.json, app/src/main.js
[Squirrel](https://github.com/Squirrel/Squirrel.Windows) is *"an installation and update framework for Windows desktop apps "*.
This PR adds `electron-squirrel-startup`, allowing to package nativefier applications 
into squirrel-based setup installers. Squirrel require this entrypoint to perform
desktop and startup menu creations, without showing the UI on setup launches.
- References: https://github.com/mongodb-js/electron-squirrel-startup
- Resolves `electron-winstaller` and `electron-installer-windows` support of desktop / startup menu shortcuts for nativefier packaged applications.
- The `electron-squirrel-startup` entrypoint has no effect on both Linux and Darwin, only on Windows
- Supporting it directly inside `nativefier` avoids having to "hack" around the existing `main.js`
and …
=> Support packaging nativefier applications into Squirrel-based installers

app/src/components/mainWindow/mainWindow.js, docs/api.md, src/build/buildApp.js, src/cli.js, src/options/optionsMain.js
- Add a new `clearCache` option and `--clear-cache` parameter
to trigger session cleanups upon window launch and close
- Covers the feature request from issue #316 
- Use case example: Forcing authentification / login between sessions without limiting cache size
=> Fix #316: Add --clear-cache flag to cleanup session on start/exit ("incognito" mode)

app/src/components/menu/menu.js
On Linux if you try to change the keyboard layout with Alt + Shift, the menu
will pop up. Shortcuts are needed because electron opens the first menu on Alt press if no hotkey assigned.
- [Similar issue](https://github.com/RocketChat/Rocket.Chat.Electron/issues/50)
=> Add Alt-key menu shortcuts

app/src/main.js
Resolve issue #664, exception encountered when using the --single-instance option. This refactors the deprecated call to app.makeSingleInstance(). See https://electronjs.org/docs/all?q=app.requestSingleInstanceLock.
=> Fix crash when launching a second instance using option --single-instance (Fixes #664)

app/src/main.js
* As explained in: https://github.com/electron/electron/issues/8862#issuecomment-294303518
an issue with .quit() exists with a "Cannot find module '../screen'" issue,
while using the .exit() alternative avoids the issue
* Validated on Windows with the same logic as #744 where the issue recently appeared
=> squirrel: resolve .quit() issue with missing ../screen

docs/api.md, package.json, src/build/buildApp.js, src/cli.js, src/constants.js, src/helpers/packagerConsole.js, src/options/optionsMain.js
This PR adds support for Dark Mode on macOS 10.4+. This was done by introducing the `--darwin-dark-mode-support` flag. Flag name is up for discussion - I kept the same flag used by Electron Packager. This also includes version bumps for Electron and Electron Packager (necessary for Dark Mode support).
Addresses:
- https://github.com/jiahaog/nativefier/issues/733
- https://github.com/jiahaog/nativefier/issues/727
=> Support macOS 10.4+ Dark Mode, default to Electron 5.x

app/src/components/mainWindow/mainWindow.js, docs/api.md, src/build/buildApp.js, src/cli.js, src/options/optionsMain.js
Closes issue #795
Adds a backgroundColor flag for the background of the window when the app isn't loaded
=> Support setting background color (fixes #795)

app/src/components/mainWindow/mainWindow.js, docs/api.md, src/build/buildApp.js, src/cli.js, src/helpers/packagerConsole.js, src/options/optionsMain.js
This PR adds a new option to the CLI (`--browserwindow-options`), taking a stringified JSON object as input.  
It will be inserted directly into the options when BrowserConfig is initialised in `/app/src/components/mainWindow/mainWindow.js`.
This allows total configurability of the electron BrowserWindow configuration via `nativefier`.
An example use case is added to the documentation, which modifies the default font family in the browser.
- https://github.com/electron/electron/blob/master/docs/api/browser-window.md#new-browserwindowoptions
- See the following for electron v3.1.7
- https://github.com/electron/electron/blob/v3.1.7/docs/api/browser-window.md#new-browserwindowoptions
=> Add --browserwindow-options to completely expose Electron options

app/src/components/login/loginWindow.js
nodeIntegration is required if eg. Javascript code makes use of the
`require` expression to import classes into the current scope. login.js
uses an electron import - without it, the callback mechanism does not
work, and thus the whole login functionality.
Electron seems to have changed the default value for a windows `nodeIntegration` to `false` since version 5 (see https://stackoverflow.com/questions/55093700/electron-5-0-0-uncaught-referenceerror-require-is-not-defined)
Without the integration, the login component's functionality is broken, though. This PR enables the nodeIntegration feature for the login window and makes it properly propagate the given credentials.
Tested with Electron 6.0.0 on Linux.
=> Restore login functionality broken since Electron 5.x

app/src/components/mainWindow/mainWindow.js
**Resolves #855**
**Example result upon Terminal launch:**
`WARNING: Ignored nativefier.json rewrital (Error: EACCES: permission denied, open '/usr/lib/jupyter-remote-client/resources/app/nativefier.json')`
**Behaviour:**
+ Instead of crashing, the application properly opens and is always maximized.
+ When permissions are R/W, the application is maximized on first launch and the closing states are remembered by the OS throughout launches.
=> app: handle nativefier.json readonly access with options.maximize (Issue #855)

app/src/components/menu/menu.js
**Resolves #875**
**Details:**
* Electron 5.0 always defines a default application menu
* The menu.js safeguard ignores nativefier's menu due to this new default menu
* The safeguard removal allows the nativefier menu to be created
* The nativefier menu respects `disableDevTools = true` as before
=> app: fix: nativefier application menu support on Electron 5.0

src/utils/sanitizeFilename.js, src/utils/sanitizeFilename.test.js
For issue #708 
- Changed Kebab casing to removal of space in string for the specific case of Linux platform
- For the issue specifying the directory name as `win32-x64`, I'm not sure if we can edit the platform name directly, since it is the convention followed by electron in its naming.
- Corresponding test also edited as well.
=> Fix weirdly platform-dependent folder naming logic (PR #850, fix #708)

app/src/components/trayIcon/trayIcon.js
The API `tray.setHighlightMode(mode)` has been be removed in electron v7.0
without replacement.
This causes the display of an error dialog every time an app is
shown/hidden if the parameter `--tray` is used when nativefying. This is
completely independent form the website you are nativefying and it
happens with all the version of electron after 6.x.
source: https://www.electronjs.org/docs/api/breaking-changes#tray
=> Fix #903: JS error when using Electron 7+ and --tray (PR #904)

app/src/main.ts, app/src/preload.ts, package.json, src/cli.ts
1. Fix (broken since 2016): Notifications broken by lambda constructor
2. Fix: `--processEnvs` broken by additional processEnvs object, the result was:
`processEnvs: {processEnvs: {...}}` which caused the conversion of the inner object into string `[object Object]`, no nesting allowed there probably. Compatibility introduced.
3. Fix: package.json missing `prepare` (or even prepublish), which breaks using as git dependency.
=> Fix: notifications (fix #88, fix #956), processEnvs, using as git

src/cli.ts
- correct small typo (`he`→`the`)
- clarify that `--icon` accepts .icns on macOS
=> Correct small typo, and clarify helptext

Dockerfile
Updated Node version in the Dockerfile from 8-stretch to 12.18.1-stretch. 12.18.1 is currently the most recent LTS version of NodeJS.
=> Bumped up NODE docker image version from 8 to 12.18.1

app/src/components/mainWindow.ts, app/src/components/mainWindowHelpers.test.ts, app/src/components/mainWindowHelpers.ts, docs/api.md, src/build/prepareElectronApp.ts, src/cli.ts, src/options/model.ts, src/options/optionsMain.ts
Fixes #978 
Adds a `--block-external-urls` option (default: `false`) that prevents opening external links (as classified by the `--internal-urls` option).
Documentation and tests updated.
Example:
```
nativefier --internal-urls "classroom\.google\.com" --block-external-urls
```
=> Add `--block-external-urls` flag to forbid external navigation attempts (fix #978)

docs/development.md, package.json
I noticed that the development README suggested using multiple console windows/tabs for a good development experience.  Using the package `concurrently`, we can streamline that and require only one window with output for both watch processes:
=> [dev] Add unified {build,test} watch mode, using "concurrently"

src/build/buildNativefierApp.ts, src/options/model.ts, tsconfig.json
This PR adds better Typescript support when using the Node module directly:
1. Generate type declarations when running `tsc`
2. Created the `NativefierOptions` type for the `buildNativefierApp` function instead of using `any`
=> Typescript types

src/constants.ts
Fixes [CVE-2020-15999](https://github.com/advisories/GHSA-pv36-h7jh-qm62) Heap overflow in the freetype library by upgrading to Electron [10.1.5](https://github.com/electron/electron/releases/tag/v10.1.5) 
https://github.com/electron/electron/pull/26070
=> Bump default Electron to 10.1.5 (with Chromium 85.0.4183.121)

app/src/components/mainWindow.ts
Correctly handle window options when both `--maximize` and `--tray start-in-tray` are selected.
=> Correctly start in tray when both --maximize and --tray start-in-tray are passed (fix #1015)

package.json
Hello! 👋
This is a tiny PR, and it just moves @types/* into dev dependencies. This doesn't effect the code, it'll just speed up installation as there are now less dependencies.
Thank you, have a great day! 😉
=> Types moved into dev dependencies

app/src/helpers/helpers.test.ts, app/src/helpers/helpers.ts, docs/api.md
In 6b266b78150, as I got rid of deprecated dep `wurl`, I wrote:
> This one may be problematic, as it used to do TLD stuff:
> https://github.com/websanova/node-url/blob/7982a613bc/wurl.js#L4
>
> So, the new WHATWG-URL-based implementation will consider
> `asana.com` to be "external" to `app.asana.com`, contrarily to before.
> Given the nature of Nativefier, I think it's actually what to expect,
> that in this case you're "out of the app", and in e.g. asana's landing
> page, which you'd expect to see in your browser.
Turns out it's even more problematic: @TheCleric notices in https://github.com/nativefier/nativefier/pull/1124#issuecomment-790279403
that this breaks app `https://evernote.com` doing its login in `www.evernote.com`
The present change fixes this, by behaving mostly similarly to …
=> Fix considering "same domain-ish" URLs as internal

.dockerignore, Dockerfile
Per the [note](https://github.com/nativefier/nativefier/pull/1122#discussion_r588922780) by @SuperSandro2000 in #1122 Docker will still cache files in intermediate layers if you delete them, so they'll still be part of the image.
Only solution seems to be to delete them as you create them so they don't cache:
Per https://stackoverflow.com/questions/53998310/docker-remove-file-from-intermediate-layer
=> Docker: slim down image size, by removing temp/cache files

app/src/components/mainWindow.ts, docs/api.md
As discussed in #283 this PR will allow injected JS to do SOME interaction with the Electron session.
There should be a full explanation of what this feature can, and cannot, do with examples in the api.md documentation.
As well, I feel like this will provide a path for resolving many of our issues where users may "self-service" the solution by injecting JS that performs the task needed to meet their objectives.
=> Add a `session-interaction` event to allow injected js to interact with apps Electron `session` object

app/src/helpers/helpers.test.ts, app/src/helpers/helpers.ts
I have 2FA (FIDO/Yubikey) set up for GitHub, and the session login was redirecting to my browser. Looking at the redirect path, it appears that github.com/session is involved, so adding that to internal login details.
With this patched, I'm able to login in to https://octobox.io/ in nativefier.
=> Automatically-internal login URLs: add GitHub 2FA pages

app/src/helpers/helpers.test.ts, app/src/helpers/helpers.ts
Used by [Notion](https://www.notion.so/login), for example. TLDs other than `.com` don't appear to exist.
=> Add Apple ID to automatically-internal login pages

app/src/components/mainWindow.ts, app/src/components/menu.ts, docs/api.md, src/build/prepareElectronApp.ts, src/cli.ts, src/options/model.ts, src/options/optionsMain.ts
This PR adds an optional, customizable menu of predefined bookmarks. In addition to containing a list of bookmarks, this file customizes the name of the menu and (optionally) allows assigning keyboard shortcuts to bookmarks. It adds a new command-line flag, `--bookmarks-menu <string>`, which can be set as the path to a JSON file containing configuration for the bookmarks menu.
Example of such a JSON file:
```json
{
"menuLabel": "Music",
"bookmarks": [
{
"title": "lofi.cafe",
"url": "https://lofi.cafe/",
"type": "link",
"shortcut": "Cmd+1"
},
{
"title": "beats to relax/study to",
"url": "https://www.youtube.com/watch?v=5qap5aO4i9A",
"type": "link",
"shortcut": "Cmd+2"
},
{
"type": "separator"
},
{
"title": "RÜFÜS DU SOL Live from Joshua Tree",
"type": "link",
"url": …
```
=> Support defining a custom bookmarks menu (fix #1065)

docs/api.md
When I added this documentation originally, I guess I placed it in the wrong location. MY BAD!
=> Move misplaced shortcuts macos documentation

app/src/components/trayIcon.ts, docs/api.md, icon-scripts/convertToTrayIcon, src/build/buildIcon.ts, src/build/buildNativefierApp.ts, src/helpers/iconShellHelpers.ts
This PR is meant to fix a startup crash on macOS when using the --tray cli option, it's mentioned in #527.
It will also accomplish to correctly display the tray icon on macOS, which would close #942 and #668.  
Example:
`
nativefier "web.whatsapp.com" --tray
`
=> macOS: Fix crash when using --tray (fix #527), and invisible icon (fix #942, fix #668)

app/src/components/mainWindow.ts, app/src/main.ts
Should alleviate part of the issue in #1151
=> Prompt to confirm when page is attempting to prevent unload

.github/ISSUE_TEMPLATE/bug_report.md, README.md
Per #1112, I'm adding some common troubleshooting steps to the README. As well, this adds a checkbox requesting users to check this section before submitting a ticket, which will hopefully lead to more self-help.
=> README: add troubleshooting section for common issues

.eslintrc.js, app/.eslintrc.js, app/package.json, app/src/components/mainWindow.ts, app/src/components/menu.ts, app/src/components/trayIcon.ts, app/src/helpers/helpers.ts, app/src/helpers/inferFlash.ts, app/src/main.ts, app/src/preload.ts, package.json, src/build/prepareElectronApp.ts, src/cli.ts
In reference to request in https://github.com/nativefier/nativefier/pull/1168/files#r623753290 ,
this PR fixes a lot of the disparity in logging, and fleshes the logging out a bit.
=> App: replace console.xyz calls with loglevel.xyz, with a level controlled by app argv --verbose

.eslintrc.js, app/src/preload.ts
=> Fix crash in preload.js due to 3rd-party 'loglevel' (fix #1175, fix #1176)

src/build/prepareElectronApp.test.ts, src/build/prepareElectronApp.ts
This is a follow-up of https://github.com/nativefier/nativefier/pull/1162#discussion_r623766247
PR #1162 introduced a new `generateRandomSuffix` helper function,
used it for its needs (avoiding collisions of injected js/css).
But it also replaced existing appname normalizing logic with it,
introducing randomness in a place that used to be deterministic.
As a result, starting with dd6e15fb5 / v43.1.0, re-creating an app would cause
the app to use a different appName, thus a different appData folder, thus
losing user data including cookies.
This PR leaves the `--inject` fixes of #1176, but reverts the appName logic
to the pre-#1176 code.
=> Fix logging out users on upgrade / app recreate with same URL (fix #1176)

CATALOG.md, README.md
Added the CATALOG.md file and updated the README.md file Usage section to link to the new file.
=> CATALOG.md: build command library (fix #1166)

.gitignore, app/package.json, app/src/helpers/helpers.test.ts, app/src/helpers/helpers.ts
Domain-ish URL test now also covers URLs with different sub-domains
- `https://listen.tidal.com`
- `https://login.tidal.com`
=> linkIsInternal: consider shop.foo.com and blog.foo.com as internal (still without extra dep or SLD list)

CATALOG.md
Google apps hint taken from https://github.com/nativefier/nativefier/issues/831#issuecomment-839899360
Also,
- copy / cleanup / conciseness
- commands indentation
- using single quotes to avoid escaping double-quotes
- add markdown subsyntax hint for nativefier calls
- remove subsections for more clarity of sections & more vertical compactness.
=> CATALOG.md: cleanup & add Google apps section

.github/workflows/ci.yml, .gitignore, package.json, tsconfig.json
As Node 10 is deprecated, this PR moves our minimum required version of node to 12.0.0 and npm to 6.9.0 (which is the version of npm that was released with node 12.0.0)
=> Bump minimum required version: node>=12.9, npm>=6.9

app/src/main.ts
@ronjouch this PR probably seems like overkill but it accomplishes two things:
- Eliminating the global mainWindow variable so weird scoping bugs like this can't happen
- More importantly: I also discovered a bug where the widevine events and non-widevine ready event were embedded within an unrelated if/else block. See: https://github.com/nativefier/nativefier/blob/72de7b3/app/src/main.ts#L235-L262 and look at their parent if/else block.
=> Eliminate need for global mainWindow, refactor widevine / non-widevine events

app/src/helpers/helpers.ts, app/src/helpers/windowHelpers.test.ts, app/src/helpers/windowHelpers.ts
When debugging other issues recently, I noticed that we are VERY aggressive with trying to inject CSS. This came in a few forms:
- We try to inject CSS as long as we have an inject directory (regardless of whether there is CSS in it), which now seems to always return true as we have a placeholder file in there now.
- We try to inject CSS on ANY network call (whether CSS is relevant or not).
So this PR tweaks this so that we will now:
- Check for actual CSS to see if we have anything to inject
- Check the http method and resource type of the requests we're monitoring and blacklist the following from CSS injection as unnecessary:
- METHOD: DELETE
- MEtHOD: OPTIONS
- RESOURCE TYPE: image
- RESOURCE TYPE: script
- RESOURCE TYPE: stylesheet
- RESOURCE TYPE: xhr
- Add unit tests for these
I …
=> Selective css injection

app/src/components/trayIcon.ts, app/src/helpers/windowHelpers.ts, src/build/buildIcon.ts, src/build/buildNativefierApp.ts, src/cli.test.ts, src/cli.ts, src/integration-test.ts, src/options/fields/fields.test.ts, src/options/model.ts, src/options/optionsMain.test.ts, src/options/optionsMain.ts
By tightening up typing and logic around tray options.
To be honest @ronjouch this code feels dirty to me. Instead of this hybrid string/boolean param. If I had my way I'd probably split this into two boolean params: `--tray` and `--start-in-tray` to keep all of this a lot cleaner.
=> Fix app keeping running in the background after closed (--tray false regression)

app/src/main.ts
The current check for `count` means the value to reset/remove the badge (`''`) is treated as `false` and therefore the badge does not get removed. This PR changes the check for `undefined` instead which resolves the issue. 
Related issue: 
https://github.com/nativefier/nativefier/issues/1251
Testing performed:
- I ran `npm t` as per the docs. All tests passed. 
- I created a new app build for Twitter (`https://twitter.com`) and Messenger (`https://messenger.com`) to verify the correct behaviour. Both were showed the issue as resolved.
=> Fix badge/counter icon not being removed correctly (fixes #1251)

app/src/helpers/windowHelpers.ts
Notification events are broken. Probably by bumping the Electron version and not handling required changes.
window.Notification is not shared with BrowserWindow and preload if contextIsolation is set.
=> Fix notification broken since Nativefier 43 / Electron 12 defaulting to contextIsolation:true

app/src/helpers/windowEvents.ts, app/src/main.ts
@ronjouch per the suggestion of @fireflinchdev , this seems to alleviate our issues with things like nuking service workers for WhatsApp. The core reason being those service workers were getting the original userAgent, and not the override (if specified). This PR should fix that.
So it should resolve #1312 #719 and hopefully a few future issues as this seems to come up frequently.
=> Use userAgentFallback for userAgent  injection

API.md, shared/src/options/model.ts, src/build/buildNativefierApp.ts, src/cli.ts, src/options/optionsMain.ts
In working on my own repo [hop](https://github.com/Nickersoft/hop), which uses nativefier under-the-hood, I found it very troublesome to suppress log output when using the programmatic API. This PR just adds a quick "quiet" option which will set the log level to "silent" and suppress all electron and nativefier output (except for errors, of course).
Let me know if there are any additional changes I need to make to get this merged!
=> Add "quiet" option to suppress all log output

HACKING.md
As discussed in https://github.com/nativefier/nativefier/issues/1258#issuecomment-1008522842 ,
here’s an attempt to formalize triage,
1. To agree on our triage practices.
2. To ease up recruiting more triagers.
=> HACKING.md: Issue triage guidelines

src/cli.ts, src/helpers/helpers.test.ts, src/helpers/helpers.ts
This fixes #1275 by assigning camel cased options in parsed arguments in the `parseArgs` function.
=> Fixes ignored --file-download-options

API.md, app/src/helpers/helpers.test.ts, app/src/helpers/helpers.ts, app/src/helpers/windowEvents.ts, shared/src/options/model.ts, src/build/prepareElectronApp.ts, src/cli.test.ts, src/cli.ts, src/options/fields/fields.test.ts, src/options/optionsMain.test.ts, src/options/optionsMain.ts
Hello, I created this so that Google Meet links don't open in my Google Calendar app for me, but it looks like others have a similar issue (e.g. issue #1304).  Feedback very welcome –– it's been awhile ;)
=> Add strict-internal-urls flag to disable domain and subpath matching

app/src/components/menu.ts, app/src/helpers/helpers.test.ts, app/src/helpers/helpers.ts
This closes #1144 by adding a "Copy as plain text" function in Edit menu.
=> Feature: Add "copy as plain text" in edit menu (fix #1144)

API.md
Old link went 404, new one has an overview of what it is and has a link to the asar github for anyone wanting technical knowledge
=> API.md: Update link for conceal flag

app/src/helpers/helpers.test.ts, app/src/helpers/helpers.ts
Fixes https://github.com/nativefier/nativefier/issues/1357 by not adding a new space when removing the app name from the User-Agent.
=> Remove extra whitespace in UserAgent (fix #1357)

src/utils/sanitizeFilename.ts
On Linux (SUSE at least), if `--name` isn't provided and is inferred,
the filename is prepended with the control character
LRM (https://en.wikipedia.org/wiki/Left-to-right_mark) and I'd assume
RLM for anyone who's using that setting.
This PR strips those control characters out of the file name.
=> Strip LRM and RLM in linux names (fix #1361)

app/src/helpers/helpers.test.ts, app/src/helpers/helpers.ts
Modify regexp to track hour counters such as `(1:23)`.
=> --counter: accept colon character (useful for time-tracking apps with hour:min)

API.md, app/src/helpers/helpers.test.ts, app/src/helpers/helpers.ts
Update internal URLs to include VMware's Workspace ONE and SecurID.
Fixes #1390
=> Include VMWare Workspace ONE SSO Internal URLs

API.md, npm-shrinkwrap.json, package.json, shared/src/options/model.ts, src/build/buildNativefierApp.ts, src/cli.ts, src/infer/inferOs.ts, src/integration-test.ts, src/options/fields/fields.test.ts, src/options/optionsMain.test.ts
Resolves #1384 
As noted in `API.md`:
- When specifying `universal` you must be building for the `darwin`, `mas`, `mac`, or `osx` platforms. This will generate a universal (M1 and x86) app.
=> macOS: universal architecture app support (fix #1384)

app/src/main.ts
=> Handle 'open-url' event: support "deep-linking" e.g. for mailto links (fix #1412)

CATALOG.md
I've used Nativefier along with Notion in the last couple days and I was able to use interactive buttons on my Notion exported page, something that was not possible originally. As such, please consider the following recipe.
=> CATALOG.md: add a new recipe for using interactive buttons on Notion

app/npm-shrinkwrap.json, app/package.json, npm-shrinkwrap.json, package.json, src/constants.ts
https://www.electronjs.org/docs/latest/breaking-changes#planned-breaking-api-changes-190
https://github.com/electron/electron/releases/tag/v19.0.0
https://github.com/electron/electron/releases/tag/v19.0.1
https://github.com/electron/electron/releases/tag/v19.0.2
https://github.com/electron/electron/releases/tag/v19.0.3
https://github.com/electron/electron/releases/tag/v19.0.4
https://github.com/electron/electron/releases/tag/v19.0.5
https://github.com/electron/electron/releases/tag/v19.0.6
https://github.com/electron/electron/releases/tag/v19.0.7
https://github.com/electron/electron/releases/tag/v19.0.8
https://github.com/electron/electron/releases/tag/v19.0.9
=> Major-bump default Electron from 18 to 19

API.md, src/infer/inferOs.ts, src/integration-test.ts
=> Remove ia32 as it's no longer supported in Electron 19 (fix #1439)

npm-shrinkwrap.json, package.json, src/build/buildNativefierApp.ts, src/cli.ts
Supported since [electron-packager 15.5.0](https://github.com/electron/electron-packager/releases/tag/v15.5.0).
This should fix #1405  as well
=> macOS: Move handling of "universal" apps to electron-packager instead of our own thing

CATALOG.md
I wasted some time trying to setup Microsoft Teams using nativefier, and some issues pointed me in the right direction. I decided to not only stop there, but to inject some css to hide some unnecessary elements from a desktop app, like an app download button and a waffle button that sits on the top left corner.
=> Microsoft Teams with custom css injected

app/src/components/mainWindow.ts
Fix for [Maximize window visual glitch on Windows · Issue #1447 · nativefier/nativefier](https://github.com/nativefier/nativefier/issues/1447)
=> Maximize window visual glitch on Windows fix (fix #1447)

.github/manual-test, app/src/components/mainWindow.ts, app/src/helpers/helpers.ts, app/src/main.ts, app/src/preload.ts
I'm picking up @RickStanley's abandoned PR #1321 again to add screensharing support (fixes #927), with the following additional changes:
- In newer Electron versions, `desktopCapturer.getSources` must be called from the main process, so I solved this with an IPC call.
- Importing from `./helpers/helpers` in 'preload.ts' does not work, as was mentioned by @DimICE in https://github.com/nativefier/nativefier/pull/1321#issuecomment-1001518035. I'm not very familiar with TypeScript or Electron, so not sure why that is and how it could be solved - for now I just copied the referenced `isWayland` function to `preload.ts`.
- Add a screensharing test to the manual test script, as requested by @ronjouch in https://github.com/nativefier/nativefier/pull/1321#issuecomment-1006725818
As far as I …
=> Add getDisplayMedia and PipeWire support
